// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBl0HpL9sGJkgmLo81lrriVm-tUs_BMPxM',
    appId: '1:453647271162:web:38217a6235231002cef543',
    messagingSenderId: '453647271162',
    projectId: 'buri-buri-zaiemon',
    authDomain: 'buri-buri-zaiemon.firebaseapp.com',
    storageBucket: 'buri-buri-zaiemon.firebasestorage.app',
    measurementId: 'G-EHDH4PGSKD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6UixlOXaP9jtMbVj5WW3zj5TkaN03rUg',
    appId: '1:453647271162:android:9bb476404551d839cef543',
    messagingSenderId: '453647271162',
    projectId: 'buri-buri-zaiemon',
    storageBucket: 'buri-buri-zaiemon.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrQ-6z4guEmZNyWbZeiFc5XRuuzKV5wxA',
    appId: '1:453647271162:ios:bff6e10f703bb17acef543',
    messagingSenderId: '453647271162',
    projectId: 'buri-buri-zaiemon',
    storageBucket: 'buri-buri-zaiemon.firebasestorage.app',
    iosBundleId: 'com.example.bussinessByJinn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrQ-6z4guEmZNyWbZeiFc5XRuuzKV5wxA',
    appId: '1:453647271162:ios:bff6e10f703bb17acef543',
    messagingSenderId: '453647271162',
    projectId: 'buri-buri-zaiemon',
    storageBucket: 'buri-buri-zaiemon.firebasestorage.app',
    iosBundleId: 'com.example.bussinessByJinn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBl0HpL9sGJkgmLo81lrriVm-tUs_BMPxM',
    appId: '1:453647271162:web:9765fe69840a95e1cef543',
    messagingSenderId: '453647271162',
    projectId: 'buri-buri-zaiemon',
    authDomain: 'buri-buri-zaiemon.firebaseapp.com',
    storageBucket: 'buri-buri-zaiemon.firebasestorage.app',
    measurementId: 'G-2EN60BTHJX',
  );
}
